### ISSUE TITLE
Use a Docker container environment when building LinuxBoot in the CI

### ISSUE THREAD

**Issue by rjoleary** [linuxboot/mainboards#44]
Tasks:

1. Create a Dockerfile. See reference https://docs.docker.com/engine/reference/builder/. See https://github.com/u-root/u-root/blob/master/.circleci/images/test-image-amd64/Dockerfile for ideas.
2. The Dockerfile should contain the necessary tooling listed here: https://github.com/linuxboot/mainboards/blob/master/.github/workflows/ci.yml#L69
3. Follow instructions here for creating a container action: https://docs.github.com/en/actions/creating-actions/creating-a-docker-container-action
4. Use the `container` field to make use of the container: https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idcontainer
5. Document the steps to update the Docker container.

**Comment by rjoleary** [comment]
Also, one important thing brought up in a recent call: It should still be possible to build the mainboards without docker. The docker container is available just to make the build system easier to download and more reproducible.

**Comment by rjoleary** [comment]
Thanks to @synackd for contributing a Dockerfile.

**Comment by orangecms** [comment]
we'll have GitHub Actions build images for us and provide simple build tools to reproduce and customize
