### ISSUE TITLE
Add an emulation/ovmf mainboard

### ISSUE THREAD

**Issue by rjoleary** [linuxboot/mainboards#45]
An OVMF mainboard would be useful to newcomers as something easy to run in QEMU without hardware.

Tasks:

1. Create option for 16MiB OVMF build. synackd mentioned he's upstreaming these changes already.
2. Create Makefile to checkout edk2 and build the image with LinuxBoot.
3. Add the mainboard to the github actions CI system.

**Comment by orangecms** [comment]
doing that now in https://github.com/linuxboot/linuxboot
