### ISSUE TITLE
Usability and further progress of Linuxboot and Rome

### ISSUE THREAD

**Issue by ShalokShalom** [linuxboot/mainboards#60]
Hi there 

Specifically asking about Rome, and also about LinuxBoot generally: How vital is this project?

Looking at the commits, it seems like Rome is stuck at 5.8, and still your most advanced platform?

**Comment by orangecms** [comment]
Hi, we're archiving this repo now and starting over with a giant overhaul.
Watch out for changes in https://github.com/linuxboot/linuxboot :-)
